all: 
	g++ -Wall -std=c++17 -O2 -c *.cpp
	g++ -Wall -std=c++17 -O2 -o main *.o -lsfml-graphics -lsfml-window -lsfml-system

debug:
	g++ -Wall -std=c++17 -Og -c *.cpp
	g++ -Wall -std=c++17 -Og -o main *.o -lsfml-graphics -lsfml-window -lsfml-system
